POST http://localhost:3000/register
Content-Type: application/json

{
    "fullName": "Jesess bond",
  "email": "Jeses@bond.com",
  "password": "123456"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "Jese@bond.com",
  "password": "123456"
}
###
GET http://localhost:3000/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1Mzc0ODI0MSwiZXhwIjoxNjUzNzUxODQxfQ.tMbQtZ09SYDDZtgRw5Zqh8HkOlUQSgAs7J3p1YA8pWs
###
POST http://localhost:3000/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1Mzc0ODI0MSwiZXhwIjoxNjUzNzUxODQxfQ.tMbQtZ09SYDDZtgRw5Zqh8HkOlUQSgAs7J3p1YA8pWs
Content-Type: application/json

{
  "name":"Easter"
}

###

POST http://localhost:3000/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1Mzc0ODI0MSwiZXhwIjoxNjUzNzUxODQxfQ.tMbQtZ09SYDDZtgRw5Zqh8HkOlUQSgAs7J3p1YA8pWs

{
"group_id": 1
}

###
GET http://localhost:3000/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1Mzc0ODI0MSwiZXhwIjoxNjUzNzUxODQxfQ.tMbQtZ09SYDDZtgRw5Zqh8HkOlUQSgAs7J3p1YA8pWs

###
GET http://localhost:3000/bills/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJpYXQiOjE2NTM3MjgzNTcsImV4cCI6MTY1MzczMTk1N30.lHkgUpMNV2jFeOj0a__rAPQJyKEnagEVK2LYbey_4eU

###
POST http://localhost:3000/bills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1MzczNzkwOCwiZXhwIjoxNjUzNzQxNTA4fQ.i5Btkwgg8G7KeGnLCQ5JCzYqcPfMDo7APl99DWWwg4s
Content-Type: application/json

{
  "groupId": 2,
  "amount": 1,
  "description": "Food"
}
